### ISSUE TITLE
Unable to install into .netstandard 2.0 library

### ISSUE THREAD

**Issue by abe545** [opentracing-contrib/csharp-netcore#12]
I'm trying to add this dependency to a helper library we use in our org, but nuget is preventing me because it has a dependency on .NETCoreApp 2.0... I was wondering if it would be possible to retarget this as a netstandard2.0 dependency.

**Comment by cwe1ss** [comment]
Unfortunately, the full .NET framework uses different code for its instrumentation in e.g. HttpClient. I haven't had the time to adopt this and to write proper unit tests so I'm currently deliberately limiting the target platform to .NET Core. Any help with this is appreciated of course!

Do you want to host your applications on the full .NET framework as well? If not, you could also consider to target "netcoreapp20" in your library.

**Comment by cwe1ss** [comment]
Because more people will ask regarding this, let me add more details on why I currently target `netcoreapp2.0` only. 

As I've written in my previous comment, unfortunately, the `HttpClient` code for .NET Core is different than for the full .NET framework: .NET Core has a [DiagnosticsHandler](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs) which uses `Activity`-based events but the full .NET framework does not have this type and still uses old, regular `DiagnosticSource` based events. I have not yet looked at Mono or other platforms so I don't know if they raise the same events. 

This means that we would have to subscribe to different `DiagnosticSource` events with different logic to support more platforms. Having support for outgoing HTTP calls is a must-have for me so I don't want to release a version that does not track outgoing HTTP calls on some platforms.

Another thing is that ASP.NET Core 2.0 and Entity Framework 2.0 introduced completely new `DiagnosticSource` events. So supporting the 1.0 versions would also require different code. Targeting `netcoreapp2.0` is an easy way to fix this as (hopefully) most people who use .NET Core 2.0 will also use the 2.0 versions of ASP.NET Core / EF Core. 

Again, I would love to target more platforms but I also want to make sure that stuff actually works and that this is covered by unit/integration tests. The issues I've just mentioned could definitely be fixed but it comes down to me having limited resources so I'm deliberatly limiting the scope for now. 

Any help is appreciated, so feel free to tell me if you want to contribute!

**Comment by abe545** [comment]
Thanks for the additional info @cwe1ss! Unfortunately for me, targeting `netcoreapp` is not an option, as this is going to be used in a full framework application, as well as .net core applications. I had no idea that .net core handled the diagnostic events differently than the full framework, and in fact know very little about the diagnostic events in general.

I know for some types that got tweaked, they either created shims or bridges. Perhaps they created some for these classes so the same code could be used? 

Since I know so little about this, I'll defer to your expertise. I'm going to try to educate myself about this stuff as I explore open tracing.

**Comment by stukselbax** [comment]
AspNetCore and EntityFrameworkCore (2.x) are both target the netstandard2.0, and instrumented with `DiagnosticSource` and `Activity`. The main reason to target `netcoreapp2.0` is the `HttpClient`. This library (_opentracing-contrib/csharp-netcore_) uses DiagnosticListener to generate traces for opentracing, so it can state it explicitly what this library for (in description of nuget package, README.md on this repo)

When `AddCoreFx(this IOpenTracingBuilder builder)` has called and the platform is not supported, there is an options to:
  - Log warning 
  - Throw an exception
  - Do nothing and wait while consumers detect this issue.
  - Provide workaround about what consumers can do to support instrumentation of `HttpClient`, for example like [zipkin4net instrument it using Microsoft.Extensions.Http](https://github.com/openzipkin/zipkin4net/blob/master/Examples/aspnetcore/frontend/Startup.cs#L15-L16)

Applications written in .net framework (old enough) probably don't use `HttpClient` at all - they have HttpWebRequest/HttpWebResponse, WebClient, and probably other tech stack (**WCF**, **.net Remoting**) to communicate over Http, which lack the `DiagnosticSource` instrumentation.

As you said about the different events used by AspNetCore and EntityFrameworkCore 1.x and 2.x, so the code can be added to detect which version is in use and select correct one events (hope there should be similarities between events and their names) - or - throw an exception / log warning and do not support 1.x.

@cwe1ss what do you think? will you accept the PR with such kind of changes?

**Comment by dmccaffery** [comment]
Another option is to use a delegating handler in the HttpClient pipeline to avoid the need to rely on diagnostics. Users of this library would need to register the delegating handler within the pipeline as an extra step, but it would work everywhere HttpClient is used then (including full framework and .net core)

**Comment by dmccaffery** [comment]
As an FYI, this is easy to do within IOC when using the HttpClientFactory: 

https://github.com/aspnet/Extensions/blob/c19b309cd8839c4e572a7fc10ae873b4c7ee1f93/src/HttpClientFactory/samples/HttpClientFactorySample/Program.cs#L90

this could be something like:

.AddHttpMessageHandler(() => new OpenTracingHandler());

**Comment by megakid** [comment]
I too need a `netstandard2.0` library so I can use this in our framework libs.  I would be happy to do some of the work if the PR would be looked at

**Comment by kzeitz** [comment]
Adding support for netstandard 2.0 would certainly increase the usefulness of the library.  I use this in a package that wraps up the tracing needs for our Nomad environment.  Sure would like to support both my netcore 2 and 3 clients with the same package.

**Comment by austinlparker** [comment]
We'd be happy to review a PR if anyone wanted to do work on this, but I don't think any of the maintainers have the time to do any of the work at this point.

**Comment by kzeitz** [comment]
I'll let you know how this works out...  So far changing
`<TargetFrameworks>netcoreapp2.0</TargetFrameworks>`
to
`<TargetFrameworks>netstandard2.0</TargetFrameworks>`

Is all that was needed.  Of course I'm still targeting netcore 2.x and 3.x

**Comment by cwe1ss** [comment]
I don't think this library will ever target .NET Standard 2.0 unless there's someone who wants to create a PR with tests for the .NET Framework (which is probably wasted time with OpenTelemetry being in beta now).

The way forward is .NET 5. If it's not much work, I might try multi-targeting "netcoreapp2.1;netcoreapp3.1;net5.0". In that case, you would also be able to use it in .NET 5 class libraries.

But targeting .NET 5 is a different topic so I'm closing this issue.
