### ISSUE TITLE
Make injection format configurable through HttpHandlerDiagnosticOptions.cs

### ISSUE THREAD

**Issue by setagana** [opentracing-contrib/csharp-netcore#47]
Hi there,

I'm running into some issues using the package in Azure App Services because the HTTP headers seem to be being stripped out of my requests (I think). 

I've [turned to stackoverflow](https://stackoverflow.com/questions/57419866/azure-app-service-removing-jaeger-http-headers-from-inter-service-requests) to try and help me resolve that, but it wouldn't be an issue if I could choose one of the other injection formats through the HttpHandlerDiagnosticOptions class. 

Would be great if you guys could consider adding that as an option.

**Comment by austinlparker** [comment]
Thanks for opening the issue! We'd gladly accept a PR for this - work is a bit slow on this plugin as we're focusing a lot of effort onto OpenTelemetry.

**Comment by cwe1ss** [comment]
Hi, this library relies on the tracer to set the proper correlation headers. It just calls `ITracer.Inject` with `BuiltinFormats.HttpHeaders` and the tracer you use has to interpret that. You therefore need to configure your tracer to use the format you like. 

(Same is valid for parsing incoming headers in ASP.NET Core requests, where `ITracer.Extract` is called).

Please let me know if this doesn't help and this issue is still relevant to you.
